import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MantineProvider } from '@mantine/core'; // Импортируем MantineProvider
import '@mantine/core/styles.css'; // Импортируем стили Mantine

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* Оборачиваем все приложение в MantineProvider */}
      <MantineProvider withGlobalStyles withNormalizeCSS>
        {children}
      </MantineProvider>
      </body>
      </html>
  );
}
